version: '3.3'
services:
  nginx:
    image: nginx:1.21-alpine
    restart: on-failure
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  hls_encoder:
    build:
      context: .
    restart: on-failure
    command: ffmpeg -y -i 'https://radiohq.stream.aripisprecer.ro/radio.mp3;' -c:a:0 libfdk_aac -profile:a:0 aac_he_v2 -b:a:0 32k -c:a:1 libfdk_aac -profile:a:1 aac_he_v2 -b:a:1 64k -c:a:2 libfdk_aac -profile:a:2 aac_he_v2 -b:a:2 128k -c:a:3 libmp3lame -b:a:3 320k -async 1 -ac 2 -r 44100 -map 0:a:0 -map 0:a:0 -map 0:a:0 -map 0:a:0 -f hls -hls_init_time 2 -hls_time 6 -hls_list_size 5 -hls_delete_threshold 10 -master_pl_name index.m3u8 -var_stream_map 'a:0,name:very_low,agroup:very_low a:1,name:low,agroup:low,default:yes a:2,name:medium,agroup:medium a:3,name:high,agroup:high' -hls_flags delete_segments+omit_endlist -hls_start_number_source epoch -master_pl_publish_rate 5 -method PUT -http_seekable 1 -http_persistent 1 -ignore_io_errors 1 -sc_threshold 0 http://nginx:80/hls/aripisprecer/%v/index.m3u8

# Useful player
# https://hls-js.netlify.app/demo/?src=http%3A%2F%2Flocalhost%3A8080%2Fhls%2Faripisprecer%2Findex.m3u8&demoConfig=eyJlbmFibGVTdHJlYW1pbmciOnRydWUsImF1dG9SZWNvdmVyRXJyb3IiOnRydWUsInN0b3BPblN0YWxsIjpmYWxzZSwiZHVtcGZNUDQiOmZhbHNlLCJsZXZlbENhcHBpbmciOi0xLCJsaW1pdE1ldHJpY3MiOi0xfQ==
